name: Trigger auto deployment for taikatranslatora1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/taikatranslatora1-AutoDeployTrigger-9029cf1d-2ea5-411a-bd8a-1172e0a7db71.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TAIKATRANSLATORA1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TAIKATRANSLATORA1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TAIKATRANSLATORA1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.TAIKATRANSLATORA1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TAIKATRANSLATORA1_REGISTRY_PASSWORD }}
          containerAppName: taikatranslatora1
          resourceGroup: TaikaTranslator
          imageToBuild: nachofzaie/taikatranslatora1:${{ github.sha }}